version: '3'

services:
  postgresdb:
    build: ./postgres
    container_name: postgresdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
    volumes:
      - db-data:/var/lib/postgresql/data

  spring-boot:
    build: .
    container_name: spring-boot
    environment:
      - DB_SERVER=postgresdb
      - DB_PORT=5432
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
    ports:
      - 8080:8080
    depends_on:
      - postgresdb
  
volumes:
  db-data: